# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the hakyll branch
  push:
    branches: [ hakyll ]
  pull_request:
    branches: [ hakyll ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Also run weekly to keep the Github cache warm, else the next deploy
  # takes >30mins
  schedule:
    - cron: '0 7 * * 1'  # 8AM CET/11PM PT on Mondays


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        cabal: ["3.10.3.0"]
        ghc: ["9.8.2"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install imagemagick and inkscape
        run: |
          sudo apt-get update
          sudo apt-get -y install imagemagick inkscape

      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: 18

      - name: Install sass
        run: npm install -g sass
          
      - uses: haskell-actions/setup@v2
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - uses: actions/cache/restore@v3
        name: Cache ~/.cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build dependencies
        run: cabal build --only-dependencies

      - uses: actions/cache/save@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}

      - name: Build site executable
        run: cabal build

      - name: Build site
        run:  cabal exec site rebuild

      - name: Deploy
        # Deploy only from non-pull-request changes to hakyll branch
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/hakyll'}}
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git checkout pages
            git pull --rebase
            # Remove old files
            ls --hide=_site | xargs -d "\n" rm -rf
            # Overwrite existing files with new files
            cp -a -v _site/. .
            #  Commit
            git add --all
            git commit --allow-empty -m "[`date '+%F %T %Z'`] New release"
            # Push
            git push origin pages:pages
